### ISSUE TITLE
Attribute table widget gets out of sync with LocalLayer widget

### ISSUE THREAD

**Issue by alaskagit** [cmndrbensisko/LocalLayer#25]
This may not be the custom widget issue, maybe a general WAB-Dev (have not yet tested if I get same results). Problem occurs when using the GUI to modify attribute tables, and I believe is tied to having possibly too many tables, or secure tables?  

When I start to modify fields to show on attribute table, on about the 6th attribute table in the list, pulls fields from a totally different table (first layer on list?).  Problem is repeatable.   Seems config file and attribute table displayed is correct.  More an issue on the GUI pulling in the data.

(See attached image) Table to modify is "Controlled-Use Areas", fields in edit window are from "UCU Codes" (first layer in list).  Several of the layers in the table will display the same incorrect fields. 
 \client\server\apps##\configs\AttributeTable\config_Attribute_Table.json  can be modified to be correct and app will reflect the changes, but AttributeTable edit dialog will still be incorrect.

Is this a LocalLayer/Attribute issue, or a WAB.  if WAB, I can start a tech incident. Posted here first, in case this is a known issue from the widget.

![wrongattributes](https://cloud.githubusercontent.com/assets/5122433/6179142/e7db086a-b2c2-11e4-94dd-ffd23a3b4b81.PNG)

Have you seen this behavior?
Thanks

**Comment by cmndrbensisko** [comment]
If this is the same issue that I've been seeing, I'm finding this to be somewhat of a WAB issue.  If you don't mind re-configuring your fields, in order to get the Attribute Table Widget to refresh, I believe you can go into the config.json file of your application, find the entry for the Attribute Table widget (It should look something like the json snippet below):

``` javascript
{
   "uri": "widgets/AttributeTable/Widget"
   ...
}
```

And remove the "config:<config_file.json>" line from this snippet, which should look something like

``` javascript
"config": "configs/AttributeTable/config_Attribute Table.json"
```

Then try re-configuring the Attribute Table widget in builder.  It should prompt a full refresh of your services and layers, though you'll need to reconfigure your fields again.
