### ISSUE TITLE
USNG layer not loading as a feature service, but worked as a basemap?

### ISSUE THREAD

**Issue by pjdohertygis** [cmndrbensisko/LocalLayer#37]
Logging on behalf of bill.spiking@tetratech.com

This is the service in question...
http://napsg.maps.arcgis.com/home/item.html?id=dc352c5f18854d82b32bce92c0b6656b
http://maps1.arcgisonline.com/ArcGIS/rest/services/NGA_US_National_Grid/MapServer

Can someone test this to confirm? We are in the middle of an exercise but wanted to log it before we forget.

**Comment by rscheitlin** [comment]
Bill,   For you to use it as a Feature Layer you would have to specify a specific sublayer (i.e. http://maps1.arcgisonline.com/ArcGIS/rest/services/NGA_US_National_Grid/MapServer/1). I think you need to add it as a dynamic layer so that you can use http://maps1.arcgisonline.com/ArcGIS/rest/services/NGA_US_National_Grid/MapServer and load all the layers. I tested it as a dynamic layer and it work fine. Robert

**Comment by pjdohertygis** [comment]
I will check with Bill ASAP

**Comment by wspiking** [comment]
Hi Robert, I tried it again and it loaded right up for me.  I've got no idea what the issue was yesterday, the only way I could get it to load was by adding it as a base map layer.  Maybe all I needed was restart....my computer and my day.
